Train metrics for epoch {epoch}:
Average Accuracy: 0.7701
Mean Average Precision (MAP): 0.3075
Area Under ROC Curve (AUC): 0.4990
Label 1:
  Accuracy: 0.7344
  Precision: 0.7533
  Recall: 0.9636
Label 2:
  Accuracy: 0.5170
  Precision: 0.5348
  Recall: 0.6101
Label 3:
  Accuracy: 0.6729
  Precision: 0.2321
  Recall: 0.0383
Label 4:
  Accuracy: 0.8429
  Precision: 0.0926
  Recall: 0.0161
Label 5:
  Accuracy: 0.9013
  Precision: 0.1026
  Recall: 0.0208
Label 6:
  Accuracy: 0.9522
  Precision: 0.0000
  Recall: 0.0000
Epoch Loss: 0.6348
Val metrics for epoch {epoch}:
Average Accuracy: 0.7907
Mean Average Precision (MAP): 0.3065
Area Under ROC Curve (AUC): 0.5032
Label 1:
  Accuracy: 0.7542
  Precision: 0.7724
  Recall: 0.9666
Label 2:
  Accuracy: 0.5365
  Precision: 0.5423
  Recall: 0.8008
Label 3:
  Accuracy: 0.7116
  Precision: 0.2857
  Recall: 0.0159
Label 4:
  Accuracy: 0.8519
  Precision: 0.0000
  Recall: 0.0000
Label 5:
  Accuracy: 0.9181
  Precision: 0.1667
  Recall: 0.0145
Label 6:
  Accuracy: 0.9719
  Precision: 0.0000
  Recall: 0.0000
Epoch Loss: 0.5513
Train metrics for epoch {epoch}:
Average Accuracy: 0.7816
Mean Average Precision (MAP): 0.3099
Area Under ROC Curve (AUC): 0.5052
Label 1:
  Accuracy: 0.7450
  Precision: 0.7530
  Recall: 0.9853
Label 2:
  Accuracy: 0.5352
  Precision: 0.5475
  Recall: 0.6565
Label 3:
  Accuracy: 0.6835
  Precision: 0.3269
  Recall: 0.0501
Label 4:
  Accuracy: 0.8575
  Precision: 0.2105
  Recall: 0.0129
Label 5:
  Accuracy: 0.9110
  Precision: 0.1538
  Recall: 0.0104
Label 6:
  Accuracy: 0.9575
  Precision: 0.0000
  Recall: 0.0000
Epoch Loss: 0.5389
Val metrics for epoch {epoch}:
Average Accuracy: 0.7931
Mean Average Precision (MAP): 0.3056
Area Under ROC Curve (AUC): 0.5019
Label 1:
  Accuracy: 0.7598
  Precision: 0.7724
  Recall: 0.9767
Label 2:
  Accuracy: 0.5342
  Precision: 0.5344
  Recall: 0.9386
Label 3:
  Accuracy: 0.7160
  Precision: 0.2500
  Recall: 0.0040
Label 4:
  Accuracy: 0.8563
  Precision: 0.0000
  Recall: 0.0000
Label 5:
  Accuracy: 0.9192
  Precision: 0.2000
  Recall: 0.0145
Label 6:
  Accuracy: 0.9731
  Precision: 0.0000
  Recall: 0.0000
Epoch Loss: 0.5145
Train metrics for epoch {epoch}:
Average Accuracy: 0.7825
Mean Average Precision (MAP): 0.3100
Area Under ROC Curve (AUC): 0.5037
Label 1:
  Accuracy: 0.7446
  Precision: 0.7529
  Recall: 0.9848
Label 2:
  Accuracy: 0.5445
  Precision: 0.5549
  Recall: 0.6650
Label 3:
  Accuracy: 0.6830
  Precision: 0.1064
  Recall: 0.0074
Label 4:
  Accuracy: 0.8557
  Precision: 0.0588
  Recall: 0.0032
Label 5:
  Accuracy: 0.9088
  Precision: 0.1111
  Recall: 0.0104
Label 6:
  Accuracy: 0.9584
  Precision: 0.0000
  Recall: 0.0000
Epoch Loss: 0.5751
/root/miniconda3/envs/pytorch2/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
Val metrics for epoch {epoch}:
Average Accuracy: 0.7832
Mean Average Precision (MAP): 0.3050
Area Under ROC Curve (AUC): 0.4991
Label 1:
  Accuracy: 0.7609
  Precision: 0.7721
  Recall: 0.9797
Label 2:
  Accuracy: 0.5140
  Precision: 0.5306
  Recall: 0.7161
Label 3:
  Accuracy: 0.6689
  Precision: 0.2250
  Recall: 0.0717
Label 4:
  Accuracy: 0.8575
  Precision: 0.0000
  Recall: 0.0000
Label 5:
  Accuracy: 0.9226
  Precision: 0.5000
  Recall: 0.0145
Label 6:
  Accuracy: 0.9753
  Precision: 0.0000
  Recall: 0.0000
Epoch Loss: 0.5142
Train metrics for epoch {epoch}:
Average Accuracy: 0.7846
Mean Average Precision (MAP): 0.3110
Area Under ROC Curve (AUC): 0.5073
Label 1:
  Accuracy: 0.7463
  Precision: 0.7563
  Recall: 0.9795
Label 2:
  Accuracy: 0.5396
  Precision: 0.5549
  Recall: 0.6186
Label 3:
  Accuracy: 0.6906
  Precision: 0.3214
  Recall: 0.0265
Label 4:
  Accuracy: 0.8592
  Precision: 0.1111
  Recall: 0.0032
Label 5:
  Accuracy: 0.9132
  Precision: 0.2500
  Recall: 0.0104
Label 6:
  Accuracy: 0.9588
  Precision: 0.0000
  Recall: 0.0000
Epoch Loss: 0.5753
/root/miniconda3/envs/pytorch2/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
Val metrics for epoch {epoch}:
Average Accuracy: 0.7843
Mean Average Precision (MAP): 0.3059
Area Under ROC Curve (AUC): 0.5008
Label 1:
  Accuracy: 0.7643
  Precision: 0.7728
  Recall: 0.9840
Label 2:
  Accuracy: 0.5185
  Precision: 0.5386
  Recall: 0.6356
Label 3:
  Accuracy: 0.6689
  Precision: 0.2179
  Recall: 0.0677
Label 4:
  Accuracy: 0.8563
  Precision: 0.0000
  Recall: 0.0000
Label 5:
  Accuracy: 0.9226
  Precision: 0.5000
  Recall: 0.0145
Label 6:
  Accuracy: 0.9753
  Precision: 0.0000
  Recall: 0.0000
Epoch Loss: 0.4874
Train metrics for epoch {epoch}:
Average Accuracy: 0.7848
Mean Average Precision (MAP): 0.3115
Area Under ROC Curve (AUC): 0.5083
Label 1:
  Accuracy: 0.7499
  Precision: 0.7565
  Recall: 0.9859
Label 2:
  Accuracy: 0.5454
  Precision: 0.5595
  Recall: 0.6270
Label 3:
  Accuracy: 0.6906
  Precision: 0.3148
  Recall: 0.0250
Label 4:
  Accuracy: 0.8548
  Precision: 0.1600
  Recall: 0.0129
Label 5:
  Accuracy: 0.9106
  Precision: 0.0000
  Recall: 0.0000
Label 6:
  Accuracy: 0.9575
  Precision: 0.1667
  Recall: 0.0109
Epoch Loss: 0.5085
/root/miniconda3/envs/pytorch2/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
Val metrics for epoch {epoch}:
Average Accuracy: 0.7811
Mean Average Precision (MAP): 0.3043
Area Under ROC Curve (AUC): 0.4988
Label 1:
  Accuracy: 0.7609
  Precision: 0.7714
  Recall: 0.9811
Label 2:
  Accuracy: 0.5051
  Precision: 0.5336
  Recall: 0.5212
Label 3:
  Accuracy: 0.6667
  Precision: 0.2500
  Recall: 0.0916
Label 4:
  Accuracy: 0.8575
  Precision: 0.0000
  Recall: 0.0000
Label 5:
  Accuracy: 0.9214
  Precision: 0.0000
  Recall: 0.0000
Label 6:
  Accuracy: 0.9753
  Precision: 0.0000
  Recall: 0.0000
Epoch Loss: 0.4861
Exception ignored in: <function _releaseLock at 0x7fe6ec60c280>
Traceback (most recent call last):
  File "/root/miniconda3/envs/pytorch2/lib/python3.10/logging/__init__.py", line 228, in _releaseLock
    def _releaseLock():
KeyboardInterrupt:
Traceback (most recent call last):
  File "/root/miniconda3/envs/pytorch2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/root/miniconda3/envs/pytorch2/lib/python3.10/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/RadChest/code/main.py", line 78, in <module>
    main(run_name=run_name)
  File "/home/RadChest/code/main.py", line 49, in main
    GCNtrain(model=model, traindataloader=train_loader, criterion=criterion, traindataset=train_dataset, optimizer=optimizer, device=device, num_epochs=config['n_epochs'],labels=labels, valdataset= val_dataset, valdataloader=val_loader, num_workers=config['num_workers'],save_dir=save_dir, testdataloader=test_loader, testdataset=test_dataset)
  File "/home/RadChest/code/train/GCNtrain.py", line 35, in GCNtrain
    for databatch in dataloader_graph:
  File "/root/miniconda3/envs/pytorch2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/pytorch2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/root/miniconda3/envs/pytorch2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1294, in _get_data
    success, data = self._try_get_data()
  File "/root/miniconda3/envs/pytorch2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1145, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 1273817, 1273865, 1273913, 1273961, 1274009, 1274057, 1274105, 1274153, 1274201, 1274249, 1274297, 1274345, 1274393, 1274441, 1274489, 1274537) exited unexpectedly